name: angular_youtube_iframe
description: A Youtube player component for AngularDart (4+)
version: 0.1.3+1
homepage: https://github.com/rxlabz/angular_youtube_iframe
author: rxlabz <dev@rxla.bz>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: '^4.0.0'
  angular_components: '^0.7.0'
  youtube_player_interop: '^0.1.2'
  js: '^0.6.1'

dev_dependencies:
  test: ^0.12.0

transformers:
- angular